version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather_api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker_application.yml:/app/application.yml:ro
    depends_on:
      - db

  db:
    image: mysql:9.0.1
    restart: always
    volumes:
      - ./.docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ocb
    ports:
      - "3306:3306"